### ISSUE TITLE
compile with eclipse

### ISSUE THREAD

**Issue by luoyangen** [moses-smt/mosesdecoder#156]
Hi, everyone,
I wanna add feature into moses decoder, while I attempted to build with eclipse
several error raised, now the error is ld error, cannot find lmoses
I think I had done the steps given by the video of hieu hoang

**Comment by hieuhoang** [comment]
Make sure there are no compile errors otherwise it will not build the moses library, hence the 'cannot find moses'. You can read through Kenton's webpage on how to create to feature function
   http://kentonmurray.com/blogs/addingafeaturetomoses.html

The video was create by Dominik btw, not me
   https://vimeo.com/129306919

**Comment by hieuhoang** [comment]
did you manage to get it your feature to compile? With or without eclipse? If so, would like to close this issue to avoid clutter

**Comment by hieuhoang** [comment]
I'm gonna close this if you've managed to get your feature to compile

**Comment by luoyangen** [comment]
sorry i didn't check the mail. thx, i've managed to fulfill the goal.

2016-06-10 12:23 GMT+08:00 Hieu Hoang <notifications@github.com>:
