### ISSUE TITLE
filter-model-given-input.pl changes causes crash on processPhraseTableMin

### ISSUE THREAD

**Issue by VladimirSuharukov** [moses-smt/mosesdecoder#98]
New version of filter-model-given-input.pl, when it called with -Binariser processPhraseTableMin causes Segmentation fault of processPhraseTableMin (I work on Debian 3.2.63-2+deb7u1 x86_64 GNU/Linux).
I don't know how it works in other environments, but on my machine processPhraseTableMin doesn't want to take pipe object on input. I.e. somethins like this:
processPhraseTableMin -in <(cat tmp) -out res
causes seg fault.
Does it work well on other environments? Thanks!

**Comment by emjotde** [comment]
This won't work on any system. processPhraseTableMin does two passes through the data, pipes do not support that I guess?

**Comment by emjotde** [comment]
Turns out it works with "-encoding None". This produces about 20-30% bigger binary files, but does only one pass, so it works with pipes. I guess since this is for testing only, the size is not a big issue.

**Comment by emjotde** [comment]
Fixed, I believe.

**Comment by VladimirSuharukov** [comment]
Thanks! But how -encoding option affects on result file size and more important on lookup speed? Thank for quick fix!

**Comment by emjotde** [comment]
As I said, file size about 20-30% bigger than without that option. Look-up speed differences should not be noticable. What do you use the script for? It is only meant for producing mini-phrase-tables for testing/tuning purposes which should always be small and fast, regardless of the binarizer.

**Comment by VladimirSuharukov** [comment]
I don't use this script alone. It called in EMS, which I use for experiments with big models too. In question I meant why this happens, i.e. why result file bigger, but ok, it is not an important issue.

**Comment by emjotde** [comment]
It's a binary format, with -encoding None passed to the binarizer a different compression method is used. That method only does one pass through the filtered text phrase table, so it can work with pipes, but due to that it also has a worse compression rate. It is still smaller than the filtered *.gz phrase table and loads faster than the in-memory version without a binarizer. So for experiments with EMS this should make hardly any difference, a couple of MB maybe. For a final big model that you want to use for deployment on unrestricted data you should drop the -encoding None option. There the size difference can be a couple of GB.
